from typing import NewType

UserId = NewType("UserId", int)
MaxUserId = NewType("MaxUserId", int)
MaxChatId = NewType("MaxChatId", int)
OrgId = NewType("OrgId", int)
HouseId = NewType("HouseId", int)
FlatId = NewType("FlatId", int)
ResidentId = NewType("ResidentId", int)
RequestId = NewType("RequestId", int)
RequestGroupId = NewType("RequestGroupId", int)
MeterId = NewType("MeterId", int)
ReadingId = NewType("ReadingId", int)
TariffId = NewType("TariffId", int)
ChargeId = NewType("ChargeId", int)
PollId = NewType("PollId", int)
PollOptionId = NewType("PollOptionId", int)
AnnouncementId = NewType("AnnouncementId", int)
AppointmentId = NewType("AppointmentId", int)
AccessRequestId = NewType("AccessRequestId", int)
AccessSlotId = NewType("AccessSlotId", int)
AccessTargetId = NewType("AccessTargetId", int)
VerificationRequestId = NewType("VerificationRequestId", int)
EventId = NewType("EventId", int)
OrgMemberId = NewType("OrgMemberId", int)
PollVoteId = NewType("PollVoteId", int)
ReceptionWindowId = NewType("ReceptionWindowId", int)
RequestAttachmentId = NewType("RequestAttachmentId", int)
RequestStatusLogId = NewType("RequestStatusLogId", int)
RequestMessageId = NewType("RequestMessageId", int)
DemandSignalId = NewType("DemandSignalId", int)
NotificationSettingId = NewType("NotificationSettingId", int)
ChatPinId = NewType("ChatPinId", int)
ChatCardId = NewType("ChatCardId", int)

API_CHECKER_MAX_USER_ID = MaxUserId(-(10**18))
