set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]
set shell := ["sh", "-c"]

set dotenv-load := true
set dotenv-filename := "../.env"

package := "zheka"
sources := "zheka migrations tests"
slots_args := ""
bandit_args := ""
test_args := ""

default:
    @just --list

sync:
    uv sync --all-groups

lock:
    uv lock

upgrade:
    uv lock --upgrade

format:
    uv run ruff format -q .
    uv run ruff check --select COM812 --fix -q .
    uv run ruff format -q .
    uv run ruff check --select COM812 --fix -q .
    uv run ruff format -q .

ruff:
    uv run ruff check --fix .

codespell:
    uv run codespell {{sources}}

[unix]
slots:
    PYTHONPATH=. uv run slotscheck {{slots_args}} -m {{package}}

[windows]
slots:
    $env:PYTHONPATH="."; uv run slotscheck {{slots_args}} -m {{package}}

bandit:
    uv run bandit -c pyproject.toml {{bandit_args}} {{package}} -r

mypy:
    uv run mypy

lint:
    just ruff
    just codespell
    just slots
    just bandit

check:
    uv run ruff check --no-fix .
    uv run ruff format --check -q .
    just codespell
    just slots
    just bandit
    just mypy

test:
    uv run pytest --cov {{package}} {{test_args}}

tests:
    just test

all:
    just lint
    just mypy
    just test

api:
    uv run gunicorn -c gunicorn.conf.py zheka.api.asgi:app

worker:
    uv run python -m zheka.broker

seed:
    uv run python -m zheka.seed

migrate:
    uv run alembic upgrade head

downgrade:
    uv run alembic downgrade -1

migration message:
    uv run alembic revision --autogenerate -m "{{message}}"

openapi:
    uv run python scripts/export_openapi.py
