from enum import StrEnum


class TaskName(StrEnum):
    AUTO_CLOSE_REVIEWED_REQUESTS = "auto_close_reviewed_requests"
    SEND_TO_USER = "send_to_user"
    BROADCAST_TO_USERS = "broadcast_to_users"
    BROADCAST_TO_CHATS = "broadcast_to_chats"
    CREATE_BOT_REQUEST = "create_bot_request"
    TRANSCRIBE_VOICE = "transcribe_voice"
    RECOGNIZE_METER_PHOTO = "recognize_meter_photo"
    SEND_EXECUTOR_CARD = "send_executor_card"
    SEND_REVIEW_CARD = "send_review_card"
    ATTACH_RESULT_PHOTO = "attach_result_photo"
    ON_BOT_ADDED = "on_bot_added"
    WELCOME_CHAT = "welcome_chat"
    REMIND_READINGS = "remind_readings"
    REMIND_POLLS = "remind_polls"
    CLOSE_EXPIRED_POLLS = "close_expired_polls"
    WARN_VERIFICATION = "warn_verification"
    REMIND_APPOINTMENTS = "remind_appointments"
    SEND_WEEKLY_DIGESTS = "send_weekly_digests"
    BROADCAST_ACCESS_REQUEST = "broadcast_access_request"
    SEED_DEMO = "seed_demo"
    SYNC_CHAT_PINS = "sync_chat_pins"
    SYNC_CHAT_CARD = "sync_chat_card"
    KEEP_WEBHOOK = "keep_webhook"
    WATCH_REQUEST_DEADLINES = "watch_request_deadlines"
    PURGE_FILES = "purge_files"
    PURGE_IDEMPOTENCY_KEYS = "purge_idempotency_keys"
    SEND_GJI_PDF = "send_gji_pdf"
