"""resident flat number

Revision ID: e797cc037638
Revises: a72af32936f4
Create Date: 2026-09-18 00:00:23.750987

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e797cc037638"
down_revision: str | None = "a72af32936f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "residents", sa.Column("flat_number", sa.String(length=16), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("residents", "flat_number")
    # ### end Alembic commands ###
