"""initial schema

Revision ID: 317e45ecb123
Revises:
Create Date: 2026-09-20 21:52:42.644086

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "317e45ecb123"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("sound", "silent", "off", name="notification_level").create(op.get_bind())
    sa.Enum("requests", "announcements", "meters", name="notification_category").create(
        op.get_bind()
    )
    sa.Enum("pending", "approved", "rejected", name="verification_status").create(
        op.get_bind()
    )
    sa.Enum("active", "blocked", name="resident_status").create(op.get_bind())
    sa.Enum("owner", "tenant", name="resident_role").create(op.get_bind())
    sa.Enum("issue", "result", name="request_photo_kind").create(op.get_bind())
    sa.Enum("open", "closed", name="request_group_status").create(op.get_bind())
    sa.Enum("miniapp", "bot", "chat", "phone", name="request_channel").create(
        op.get_bind()
    )
    sa.Enum(
        "resident_accepted",
        "resident_rejected",
        "auto_closed",
        name="request_completion_reason",
    ).create(op.get_bind())
    sa.Enum(
        "new", "accepted", "in_progress", "on_review", "done", name="request_status"
    ).create(op.get_bind())
    sa.Enum(
        "leak",
        "elevator",
        "garbage",
        "heating",
        "water_supply",
        "electricity",
        "entrance",
        "yard",
        "meter_error",
        "charge_dispute",
        "other",
        name="request_category",
    ).create(op.get_bind())
    sa.Enum("booked", "cancelled", "done", name="appointment_status").create(
        op.get_bind()
    )
    sa.Enum("active", "closed", name="poll_status").create(op.get_bind())
    sa.Enum(
        "hot_water", "cold_water", "electricity", "gas", "heating", name="meter_type"
    ).create(op.get_bind())
    sa.Enum("creator", "admin", "employee", "executor", name="org_role").create(
        op.get_bind()
    )
    sa.Enum(
        "cold_water",
        "hot_water",
        "electricity",
        "gas",
        "heating",
        "maintenance",
        "overhaul",
        "waste",
        "penalty",
        "recalculation",
        name="service_type",
    ).create(op.get_bind())
    op.create_table(
        "organizations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("inn", sa.String(), nullable=False),
        sa.Column("license_no", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("reception_note", sa.String(), nullable=True),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("inn", name=op.f("uq_organizations_inn")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("max_user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("consent_version", sa.String(), nullable=True),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bot_stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_chat_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("max_user_id", name=op.f("uq_users_max_user_id")),
    )
    op.create_table(
        "announcements",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("house_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("channels", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("recipients_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_announcements_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_announcements_org_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
    )
    op.create_index(
        op.f("ix_announcements_house_ids"),
        "announcements",
        ["house_ids"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("type", sa.String(length=48), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(
        op.f("ix_events_type"), "events", ["type", "created_at"], unique=False
    )
    op.create_table(
        "houses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("org_id", sa.BigInteger(), nullable=True),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("street", sa.String(), nullable=False),
        sa.Column("building", sa.String(), nullable=False),
        sa.Column("cadastral_no", sa.String(), nullable=False),
        sa.Column("built_year", sa.Integer(), nullable=True),
        sa.Column("floors", sa.Integer(), nullable=True),
        sa.Column("area", sa.Integer(), nullable=True),
        sa.Column("entrances", sa.Integer(), server_default="1", nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("chat_binding_code", sa.String(length=8), nullable=False),
        sa.Column("overhaul", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("documents", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_houses_org_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_houses")),
        sa.UniqueConstraint(
            "chat_binding_code", name=op.f("uq_houses_chat_binding_code")
        ),
    )
    op.create_index(op.f("ix_houses_city"), "houses", ["city", "street"], unique=False)
    op.create_table(
        "notification_settings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM(
                "requests",
                "announcements",
                "meters",
                name="notification_category",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "level",
            postgresql.ENUM(
                "sound", "silent", "off", name="notification_level", create_type=False
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_settings_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_settings")),
        sa.UniqueConstraint(
            "user_id", "category", name=op.f("uq_notification_settings_user_id")
        ),
    )
    op.create_table(
        "org_invites",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "creator",
                "admin",
                "employee",
                "executor",
                name="org_role",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_activations", sa.Integer(), nullable=False),
        sa.Column("activations_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_org_invites_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_org_invites_org_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_org_invites")),
    )
    op.create_table(
        "org_members",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "creator",
                "admin",
                "employee",
                "executor",
                name="org_role",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_org_members_org_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_org_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_members")),
        sa.UniqueConstraint("org_id", "user_id", name=op.f("uq_org_members_org_id")),
    )
    op.create_table(
        "org_settings",
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "meter_window_day_from", sa.Integer(), server_default="15", nullable=False
        ),
        sa.Column(
            "meter_window_day_to", sa.Integer(), server_default="25", nullable=False
        ),
        sa.Column(
            "meter_window_always_open",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("group_threshold", sa.Integer(), server_default="3", nullable=False),
        sa.Column(
            "group_window_hours", sa.Integer(), server_default="24", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_org_settings_org_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("org_id", name=op.f("pk_org_settings")),
    )
    op.create_table(
        "reception_windows",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("time_from", sa.Time(), nullable=False),
        sa.Column("time_to", sa.Time(), nullable=False),
        sa.Column("slot_minutes", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_reception_windows_org_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reception_windows")),
    )
    op.create_table(
        "access_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("house_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_access_requests_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_access_requests_house_id_houses")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_access_requests_org_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_requests")),
    )
    op.create_table(
        "chats",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("house_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("bound_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "bot_is_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["bound_by"], ["users.id"], name=op.f("fk_chats_bound_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_chats_house_id_houses")
        ),
        sa.PrimaryKeyConstraint("chat_id", name=op.f("pk_chats")),
    )
    op.create_table(
        "demand_signals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("house_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_demand_signals_house_id_houses")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_demand_signals_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demand_signals")),
        sa.UniqueConstraint(
            "house_id", "user_id", name=op.f("uq_demand_signals_house_id")
        ),
    )
    op.create_table(
        "flats",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("house_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("entrance", sa.Integer(), nullable=True),
        sa.Column("area", sa.Integer(), nullable=True),
        sa.Column("account_no", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_flats_house_id_houses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flats")),
        sa.UniqueConstraint("house_id", "number", name=op.f("uq_flats_house_id")),
    )
    op.create_table(
        "polls",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("house_id", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=True),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by_role", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_multiple", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("active", "closed", name="poll_status", create_type=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_polls_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_polls_house_id_houses")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_polls_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_polls")),
    )
    op.create_table(
        "request_groups",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("house_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM(
                "leak",
                "elevator",
                "garbage",
                "heating",
                "water_supply",
                "electricity",
                "entrance",
                "yard",
                "meter_error",
                "charge_dispute",
                "other",
                name="request_category",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "open", "closed", name="request_group_status", create_type=False
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_request_groups_house_id_houses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_groups")),
    )
    op.create_table(
        "tariffs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("house_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "service",
            postgresql.ENUM(
                "cold_water",
                "hot_water",
                "electricity",
                "gas",
                "heating",
                "maintenance",
                "overhaul",
                "waste",
                "penalty",
                "recalculation",
                name="service_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("document_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_tariffs_house_id_houses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariffs")),
    )
    op.create_index(
        op.f("ix_tariffs_house_id"),
        "tariffs",
        ["house_id", "service", sa.literal_column("valid_from DESC")],
        unique=False,
    )
    op.create_table(
        "access_slots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("access_request_id", sa.BigInteger(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_request_id"],
            ["access_requests.id"],
            name=op.f("fk_access_slots_access_request_id_access_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_slots")),
    )
    op.create_table(
        "charges",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("flat_id", sa.BigInteger(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column(
            "is_closed", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["flat_id"], ["flats.id"], name=op.f("fk_charges_flat_id_flats")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charges")),
        sa.UniqueConstraint("flat_id", "period", name=op.f("uq_charges_flat_id")),
    )
    op.create_table(
        "flat_invites",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("flat_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_activations", sa.Integer(), nullable=False),
        sa.Column("activations_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_flat_invites_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["flat_id"], ["flats.id"], name=op.f("fk_flat_invites_flat_id_flats")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_flat_invites")),
    )
    op.create_table(
        "flat_verification_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("flat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("account_no", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "approved",
                "rejected",
                name="verification_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("decided_by", sa.BigInteger(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_flat_verification_requests_decided_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["flat_id"],
            ["flats.id"],
            name=op.f("fk_flat_verification_requests_flat_id_flats"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_flat_verification_requests_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flat_verification_requests")),
    )
    op.create_index(
        op.f("ix_flat_verification_requests_user_id"),
        "flat_verification_requests",
        ["user_id", "flat_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "meters",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flat_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "hot_water",
                "cold_water",
                "electricity",
                "gas",
                "heating",
                name="meter_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("tariff_zones", sa.Integer(), server_default="1", nullable=False),
        sa.Column("serial", sa.String(length=32), nullable=False),
        sa.Column("next_verification_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flat_id"], ["flats.id"], name=op.f("fk_meters_flat_id_flats")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meters")),
        sa.UniqueConstraint("flat_id", "type", name=op.f("uq_meters_flat_id")),
    )
    op.create_table(
        "poll_options",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("poll_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["poll_id"], ["polls.id"], name=op.f("fk_poll_options_poll_id_polls")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_poll_options")),
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("house_id", sa.BigInteger(), nullable=False),
        sa.Column("flat_id", sa.BigInteger(), nullable=True),
        sa.Column("author_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "category",
            postgresql.ENUM(
                "leak",
                "elevator",
                "garbage",
                "heating",
                "water_supply",
                "electricity",
                "entrance",
                "yard",
                "meter_error",
                "charge_dispute",
                "other",
                name="request_category",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "new",
                "accepted",
                "in_progress",
                "on_review",
                "done",
                name="request_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "completion_reason",
            postgresql.ENUM(
                "resident_accepted",
                "resident_rejected",
                "auto_closed",
                name="request_completion_reason",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("parent_request_id", sa.BigInteger(), nullable=True),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "channel",
            postgresql.ENUM(
                "miniapp",
                "bot",
                "chat",
                "phone",
                name="request_channel",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("caller_name", sa.String(), nullable=True),
        sa.Column("caller_phone", sa.String(), nullable=True),
        sa.Column("executor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_staff_author",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_requests_author_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["executor_user_id"],
            ["users.id"],
            name=op.f("fk_requests_executor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["flat_id"], ["flats.id"], name=op.f("fk_requests_flat_id_flats")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["request_groups.id"],
            name=op.f("fk_requests_group_id_request_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_requests_house_id_houses")
        ),
        sa.ForeignKeyConstraint(
            ["parent_request_id"],
            ["requests.id"],
            name=op.f("fk_requests_parent_request_id_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requests")),
    )
    op.create_index(
        op.f("ix_requests_executor_user_id"),
        "requests",
        ["executor_user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requests_group_id"), "requests", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_requests_house_id"), "requests", ["house_id", "status"], unique=False
    )
    op.create_table(
        "residents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("house_id", sa.BigInteger(), nullable=False),
        sa.Column("flat_id", sa.BigInteger(), nullable=True),
        sa.Column("flat_number", sa.String(length=16), nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM("owner", "tenant", name="resident_role", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "can_see_charges",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "can_vote", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active", "blocked", name="resident_status", create_type=False
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("block_reason", sa.String(), nullable=True),
        sa.Column(
            "is_chairman", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["flat_id"], ["flats.id"], name=op.f("fk_residents_flat_id_flats")
        ),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_residents_house_id_houses")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_residents_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"], ["users.id"], name=op.f("fk_residents_verified_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_residents")),
        sa.UniqueConstraint("user_id", "house_id", name=op.f("uq_residents_user_id")),
    )
    op.create_table(
        "access_targets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("access_request_id", sa.BigInteger(), nullable=False),
        sa.Column("flat_id", sa.BigInteger(), nullable=False),
        sa.Column("slot_id", sa.BigInteger(), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["access_request_id"],
            ["access_requests.id"],
            name=op.f("fk_access_targets_access_request_id_access_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["flat_id"], ["flats.id"], name=op.f("fk_access_targets_flat_id_flats")
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["access_slots.id"],
            name=op.f("fk_access_targets_slot_id_access_slots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_targets")),
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("house_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "booked",
                "cancelled",
                "done",
                name="appointment_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_appointments_house_id_houses")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_appointments_org_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_appointments_request_id_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_appointments_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    op.create_table(
        "poll_votes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("poll_id", sa.BigInteger(), nullable=False),
        sa.Column("option_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("resident_id", sa.BigInteger(), nullable=True),
        sa.Column("flat_id", sa.BigInteger(), nullable=True),
        sa.Column("counted_by_area", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flat_id"], ["flats.id"], name=op.f("fk_poll_votes_flat_id_flats")
        ),
        sa.ForeignKeyConstraint(
            ["option_id"],
            ["poll_options.id"],
            name=op.f("fk_poll_votes_option_id_poll_options"),
        ),
        sa.ForeignKeyConstraint(
            ["poll_id"], ["polls.id"], name=op.f("fk_poll_votes_poll_id_polls")
        ),
        sa.ForeignKeyConstraint(
            ["resident_id"],
            ["residents.id"],
            name=op.f("fk_poll_votes_resident_id_residents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_poll_votes_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_poll_votes")),
        sa.UniqueConstraint(
            "poll_id", "user_id", "option_id", name=op.f("uq_poll_votes_poll_id")
        ),
    )
    op.create_table(
        "readings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meter_id", sa.BigInteger(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "photo_paths", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("ocr_used", sa.Boolean(), nullable=False),
        sa.Column("ocr_accepted", sa.Boolean(), nullable=False),
        sa.Column("is_below_previous", sa.Boolean(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_by", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meter_id"], ["meters.id"], name=op.f("fk_readings_meter_id_meters")
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"], ["users.id"], name=op.f("fk_readings_submitted_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readings")),
    )
    op.create_index(
        op.f("ix_readings_meter_id"),
        "readings",
        ["meter_id", "period", sa.literal_column("submitted_at DESC")],
        unique=False,
    )
    op.create_table(
        "request_messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("author_user_id", sa.BigInteger(), nullable=False),
        sa.Column("author_role", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_request_messages_author_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_request_messages_request_id_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_messages")),
    )
    op.create_table(
        "request_photos",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("path", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "issue", "result", name="request_photo_kind", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_request_photos_request_id_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_request_photos_uploaded_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_photos")),
    )
    op.create_table(
        "request_status_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "from_status",
            postgresql.ENUM(
                "new",
                "accepted",
                "in_progress",
                "on_review",
                "done",
                name="request_status",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            postgresql.ENUM(
                "new",
                "accepted",
                "in_progress",
                "on_review",
                "done",
                name="request_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("by_role", sa.String(length=16), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["by_user_id"],
            ["users.id"],
            name=op.f("fk_request_status_log_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_request_status_log_request_id_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_status_log")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("request_status_log")
    op.drop_table("request_photos")
    op.drop_table("request_messages")
    op.drop_index(op.f("ix_readings_meter_id"), table_name="readings")
    op.drop_table("readings")
    op.drop_table("poll_votes")
    op.drop_table("appointments")
    op.drop_table("access_targets")
    op.drop_table("residents")
    op.drop_index(op.f("ix_requests_house_id"), table_name="requests")
    op.drop_index(op.f("ix_requests_group_id"), table_name="requests")
    op.drop_index(op.f("ix_requests_executor_user_id"), table_name="requests")
    op.drop_table("requests")
    op.drop_table("poll_options")
    op.drop_table("meters")
    op.drop_index(
        op.f("ix_flat_verification_requests_user_id"),
        table_name="flat_verification_requests",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("flat_verification_requests")
    op.drop_table("flat_invites")
    op.drop_table("charges")
    op.drop_table("access_slots")
    op.drop_index(op.f("ix_tariffs_house_id"), table_name="tariffs")
    op.drop_table("tariffs")
    op.drop_table("request_groups")
    op.drop_table("polls")
    op.drop_table("flats")
    op.drop_table("demand_signals")
    op.drop_table("chats")
    op.drop_table("access_requests")
    op.drop_table("reception_windows")
    op.drop_table("org_settings")
    op.drop_table("org_members")
    op.drop_table("org_invites")
    op.drop_table("notification_settings")
    op.drop_index(op.f("ix_houses_city"), table_name="houses")
    op.drop_table("houses")
    op.drop_index(op.f("ix_events_type"), table_name="events")
    op.drop_table("events")
    op.drop_index(
        op.f("ix_announcements_house_ids"),
        table_name="announcements",
        postgresql_using="gin",
    )
    op.drop_table("announcements")
    op.drop_table("users")
    op.drop_table("organizations")
    sa.Enum(
        "cold_water",
        "hot_water",
        "electricity",
        "gas",
        "heating",
        "maintenance",
        "overhaul",
        "waste",
        "penalty",
        "recalculation",
        name="service_type",
    ).drop(op.get_bind())
    sa.Enum("creator", "admin", "employee", "executor", name="org_role").drop(
        op.get_bind()
    )
    sa.Enum(
        "hot_water", "cold_water", "electricity", "gas", "heating", name="meter_type"
    ).drop(op.get_bind())
    sa.Enum("active", "closed", name="poll_status").drop(op.get_bind())
    sa.Enum("booked", "cancelled", "done", name="appointment_status").drop(
        op.get_bind()
    )
    sa.Enum(
        "leak",
        "elevator",
        "garbage",
        "heating",
        "water_supply",
        "electricity",
        "entrance",
        "yard",
        "meter_error",
        "charge_dispute",
        "other",
        name="request_category",
    ).drop(op.get_bind())
    sa.Enum(
        "new", "accepted", "in_progress", "on_review", "done", name="request_status"
    ).drop(op.get_bind())
    sa.Enum(
        "resident_accepted",
        "resident_rejected",
        "auto_closed",
        name="request_completion_reason",
    ).drop(op.get_bind())
    sa.Enum("miniapp", "bot", "chat", "phone", name="request_channel").drop(
        op.get_bind()
    )
    sa.Enum("open", "closed", name="request_group_status").drop(op.get_bind())
    sa.Enum("issue", "result", name="request_photo_kind").drop(op.get_bind())
    sa.Enum("owner", "tenant", name="resident_role").drop(op.get_bind())
    sa.Enum("active", "blocked", name="resident_status").drop(op.get_bind())
    sa.Enum("pending", "approved", "rejected", name="verification_status").drop(
        op.get_bind()
    )
    sa.Enum("requests", "announcements", "meters", name="notification_category").drop(
        op.get_bind()
    )
    sa.Enum("sound", "silent", "off", name="notification_level").drop(op.get_bind())
    # ### end Alembic commands ###
