"""add urgent to announcements

Revision ID: 89db107154e3
Revises: 317e45ecb123
Create Date: 2026-09-22 16:27:54.575120

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "89db107154e3"
down_revision: str | None = "317e45ecb123"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements",
        sa.Column(
            "urgent",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("announcements", "urgent")
    # ### end Alembic commands ###
